@startuml schema
hide circle
skinparam linetype ortho


entity "edificio" as edificio {
  * id : INT <<PK>>
  --
  nome : VARCHAR(50) [UNIQUE]
  indirizzo : VARCHAR(255)
}

entity "aula" as aula {
  * id : INT <<PK>>
  --
  * edificio_id : INT <<FK>>
  nome : VARCHAR(50)
  piano : INT
  ..
  note: UNIQUE(edificio_id, nome)
}

entity "utente" as utente {
  * id : INT <<PK>>
  --
  nome_utente : VARCHAR(50) [UNIQUE]
  password : VARCHAR(255)
  ruolo : ENUM('studente', 'tecnico', 'admin')
}

entity "segnalazione" as segnalazione {
  * id : INT <<PK>>
  --
  * utente_id : INT <<FK>>
  * aula_id : INT <<FK>>
  tecnico_id: INT <<FK>> [NULLABLE]
  titolo : VARCHAR(150)
  descrizione : TEXT
  data_apertura : TIMESTAMP
  data_chiusura : TIMESTAMP [NULLABLE]
  stato : ENUM('aperto', 'in lavorazione', 'chiuso')
  ..
  note: CHECK (data_chiusura >= data_apertura)  
}

entity "preferiti" as preferiti {
  * utente_id : INT <<PK, FK>>
  * aula_id : INT <<PK, FK>>
  --
}

' Un edificio ha molte aule
edificio ||--o{ aula : "contiene"

' Un utente (studente) crea molte segnalazioni
utente ||--o{ segnalazione : "apre"

' Un utente (tecnico) prende in carico molte segnalazioni
utente |o--o{ segnalazione : "risolve"

aula ||--o{ segnalazione : "riguarda"

utente ||--o{ preferiti
aula ||--o{ preferiti

@enduml