name: CI

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mysqli, pdo_mysql
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Check whitespace
        run: git diff --check

      - name: Run tests
        run: ./vendor/bin/phpunit --display-warnings --display-deprecations
